run:
  name: "caft-baseline"

scenario:
  clusters: [40]
  planning_horizons: [2030, 2040, 2050]

foresight: myopic

sector:
  transport: false
  heating: false
  biomass: false        
  industry: false
  shipping: false
  aviation: false
  agriculture: false
  H2_network: false
  gas_network: false
  ammonia: false
  methanation: false       
  dac: false
  SMR: false
  SMR_cc: false
  electricity_distribution_grid: true
  gas_distribution_grid: false
  biomass_spatial: false


co2_budget:
  2040: 0.1
  2050: 0.0

clustering:
  temporal:
    resolution_sector: '6h'